[package]
name = "personal_web"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-only"

[dependencies]
async-std = { version = "1.13.2", default-features = true }
dioxus = { version = "0.7.9", features = ["router", "fullstack"] }
dioxus-sdk = { version = "0.7.0", default-features = false, features = [
    "storage",
] }
fluent-langneg = { version = "0.14.2", default-features = false, optional = true }
icu_locid = { version = "1.5.0", default-features = false, optional = true }
load-dotenv = { version = "0.1.2", default-features = false }
serde = { version = "1.0.229", default-features = false }

[features]
default = ["web"]
web = ["dioxus/web"]
server = ["dioxus/server", "dep:fluent-langneg", "dep:icu_locid"]
