---
services:
  app:
    build:
      dockerfile: docker/dev/app/Dockerfile
    volumes:
      - ./assets:/srv/app/assets
      - ./src:/srv/app/src
      - ./Cargo.lock:/srv/app/Cargo.lock
      - ./Cargo.toml:/srv/app/Cargo.toml
      - ./Dioxus.toml:/srv/app/Dioxus.toml
      - ./.env:/srv/app/.env
    restart: always
    ports: ["8000:8000"]
